# Generated by Django 3.2.16 on 2023-08-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team_images')),
                ('profile', models.ManyToManyField(related_name='teams', to='account.Profile')),
                ('role', models.ManyToManyField(choices=[(1, 'Backend'), (2, 'Frontend'), (3, 'Swift'), (4, 'Python'), (5, 'Docker')], related_name='teams', to='account.Role')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'ordering': ['title'],
            },
        ),
    ]
