# Generated by Django 3.2.16 on 2023-08-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to='account.profile')),
                ('profile', models.ManyToManyField(related_name='teams', to='account.Profile')),
                ('role', models.ManyToManyField(related_name='teams', to='account.Role')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'ordering': ['title'],
            },
        ),
    ]
