# Generated by Django 3.2.16 on 2023-08-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230811_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
    ]
