# Generated by Django 3.2.16 on 2023-08-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230809_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
