# Generated by Django 3.2.16 on 2023-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
